salesforce:
  password: "![1xI+ES6wlCfkhMKwQjqxUg==]"
  token: "![+btwsJgMWUIedO797VlVto2GbV/gJ+/caFCr2JVr+U8=]"

cosmosdb:
  key: "![KE0Zqlvmqe/d5HfsUSH0f1RI5Vdk6r8i/24Yq8Rc22VT/fOd5Zo1KJlhQmIWSN2rKW8wUZIfp+4uBrgl8UuVm3VBEX+n6SG/HCooR1r7ngwzYSMgLgr3Kv8jVSnIbxzs]"
